[phases.build]
cmds = ["cd hostel && python manage.py collectstatic --no-input"]

[start]
cmd = "cd hostel && python manage.py migrate --no-input && gunicorn hostel_project.wsgi --bind 0.0.0.0:$PORT --workers 2"
