# Generated by Django 4.2.7 on 2026-05-06 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'maintenance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='maintenance_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='warden_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('furniture', 'Furniture'), ('internet', 'Internet / WiFi'), ('cleanliness', 'Cleanliness'), ('carpentry', 'Carpentry'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified by Warden'), ('forwarded', 'Forwarded to Maintenance'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=15),
        ),
        migrations.CreateModel(
            name='ComplaintTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('verified', 'Verified by Warden'), ('forwarded', 'Forwarded to Maintenance'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=15)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='complaints.complaint')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaint_timeline',
                'ordering': ['created_at'],
            },
        ),
    ]
