# Generated by Django 4.2.7 on 2026-05-06 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0037_wastage_hostel_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0002_complaint_timeline_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, help_text='Area/location for staff-reported complaints', max_length=300),
        ),
        migrations.AddField(
            model_name='complaint',
            name='raised_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('furniture', 'Furniture'), ('internet', 'Internet / WiFi'), ('cleanliness', 'Cleanliness'), ('carpentry', 'Carpentry'), ('infrastructure', 'Infrastructure'), ('civil', 'Civil Work'), ('painting', 'Painting / Whitewash'), ('pest_control', 'Pest Control'), ('ac', 'AC / HVAC'), ('security_infra', 'Security Infrastructure'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.student'),
        ),
    ]
