# Generated by Django 4.2.7 on 2026-06-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_staff_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified by Warden'), ('forwarded', 'Forwarded to Maintenance'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=15),
        ),
        migrations.AlterField(
            model_name='complainttimeline',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('verified', 'Verified by Warden'), ('forwarded', 'Forwarded to Maintenance'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=15),
        ),
    ]
