# Generated by Django 4.2.7 on 2026-04-01 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(help_text='e.g. Indian, International, Boys, General', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('max_preferences', models.PositiveSmallIntegerField(default=3, help_text='How many room preferences the student can specify')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reg_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registration_forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='submitted', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('allocated_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_allocations', to='hostel.room')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hostel.registrationform')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_submissions', to='hostel.student')),
            ],
            options={
                'db_table': 'registration_submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('form', 'student')},
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes')], default='text', max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options list for select/radio/checkbox fields')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='hostel.registrationform')),
            ],
            options={
                'db_table': 'form_fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.formfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hostel.registrationsubmission')),
            ],
            options={
                'db_table': 'submission_responses',
                'unique_together': {('submission', 'field')},
            },
        ),
        migrations.CreateModel(
            name='RoomPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference_number', models.PositiveSmallIntegerField()),
                ('room_type', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=10)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.hostel')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='hostel.registrationsubmission')),
            ],
            options={
                'db_table': 'room_preferences',
                'ordering': ['preference_number'],
                'unique_together': {('submission', 'preference_number')},
            },
        ),
    ]
