# Generated by Django 4.2.7 on 2026-04-06 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0005_student_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('destination', models.CharField(max_length=300)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('expected_return_date', models.DateField()),
                ('expected_return_time', models.TimeField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded'), ('returned', 'Returned')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_to', models.CharField(blank=True, help_text='Name/designation of authority forwarded to', max_length=200)),
                ('forward_notes', models.TextField(blank=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gate_passes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_passes', to='hostel.student')),
            ],
            options={
                'db_table': 'gate_passes',
                'ordering': ['-created_at'],
            },
        ),
    ]
