# Generated by Django 4.2.7 on 2026-04-07 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0006_gate_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='actual_return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='hod_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_gate_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='is_overstayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='pass_type',
            field=models.CharField(choices=[('day_outing', 'Day Outing'), ('overnight', 'Overnight Leave'), ('emergency', 'Emergency Leave')], default='day_outing', max_length=15),
        ),
        migrations.AddField(
            model_name='room',
            name='wing',
            field=models.CharField(blank=True, help_text='e.g. A-Wing, North Block', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='aadhar_doc',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/aadhar/'),
        ),
        migrations.AddField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='college_id_doc',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/college_id/'),
        ),
        migrations.AddField(
            model_name='student',
            name='college_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='forwarded_to',
            field=models.CharField(blank=True, help_text='Name/designation of HOD/Authority forwarded to', max_length=200),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded to HOD'), ('hod_approved', 'HOD Approved'), ('returned', 'Returned')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='Standard', help_text='Admin-defined type e.g. AC Double, Non-AC Triple, VIP', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='vacant', max_length=15),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=150)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('guardian', 'Guardian'), ('relative', 'Relative'), ('friend', 'Friend'), ('other', 'Other')], max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('id_proof_type', models.CharField(default='Aadhar', help_text='Aadhar, PAN, DL, Passport, etc.', max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('visit_date', models.DateField()),
                ('expected_in_time', models.TimeField()),
                ('expected_out_time', models.TimeField()),
                ('actual_in_time', models.DateTimeField(blank=True, null=True)),
                ('actual_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='pending', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitors', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='hostel.hostel')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='hostel.student')),
            ],
            options={
                'db_table': 'visitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('announcement', 'Announcement'), ('gate_pass', 'Gate Pass'), ('complaint', 'Complaint'), ('visitor', 'Visitor'), ('discipline', 'Discipline'), ('mess', 'Mess'), ('general', 'General')], default='general', max_length=15)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Evening Snacks'), ('dinner', 'Dinner')], max_length=15)),
                ('items', models.TextField(help_text='Comma-separated or bullet list of items')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_menus', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(blank=True, help_text='Leave blank to apply to all hostels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='hostel.hostel')),
            ],
            options={
                'db_table': 'mess_menus',
                'ordering': ['day', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('furniture', 'Furniture'), ('cleaning', 'Cleaning'), ('network', 'Network/Internet'), ('other', 'Other')], max_length=15)),
                ('issue', models.TextField()),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='hostel.room')),
            ],
            options={
                'db_table': 'maintenance_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fine_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('appealed', 'Appealed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='hostel.student')),
            ],
            options={
                'db_table': 'discipline_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(help_text='e.g. A, B, 1, 2', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='available', max_length=15)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.room')),
            ],
            options={
                'db_table': 'beds',
                'ordering': ['room', 'bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='hostel.bed'),
        ),
        migrations.CreateModel(
            name='MessFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Evening Snacks'), ('dinner', 'Dinner')], max_length=15)),
                ('rating', models.PositiveSmallIntegerField(help_text='1 (Poor) to 5 (Excellent)')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_feedback', to='hostel.student')),
            ],
            options={
                'db_table': 'mess_feedback',
                'ordering': ['-date'],
                'unique_together': {('student', 'date', 'meal_type')},
            },
        ),
    ]
