# Generated by Django 4.2.7 on 2026-04-09 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0008_semester_reallotment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Fan, Cupboard, Table, Chair', max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='good', max_length=10)),
                ('asset_tag', models.CharField(blank=True, help_text='Asset ID / Serial number', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assets', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='hostel.room')),
            ],
            options={
                'db_table': 'room_assets',
                'ordering': ['name'],
            },
        ),
    ]
