# Generated by Django 4.2.7 on 2026-04-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_room_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='monthly_fee',
        ),
    ]
