# Generated by Django 4.2.7 on 2026-04-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_remove_room_monthly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='type',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('staff', 'Staff')], max_length=5),
        ),
    ]
