# Generated by Django 4.2.7 on 2026-04-11 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0011_add_staff_hostel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='entry_allowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_allowed_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='entry_qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='entry_qr_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='entry_qr_token',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='exit_allowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_allowed_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='exit_qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='exit_qr_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='exit_qr_token',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
