# Generated by Django 4.2.7 on 2026-04-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_qr_gate_pass_security_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='forward_notes',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='forwarded_to',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='hod_approved_at',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='hod_approved_by',
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=15),
        ),
    ]
