# Generated by Django 4.2.7 on 2026-04-11 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0013_remove_hod_forwarded_gatepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='guard_entry_permitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='guard_entry_permitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='guard_entry_permitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_permitted_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='guard_exit_permitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='guard_exit_permitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='guard_exit_permitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_permitted_passes', to=settings.AUTH_USER_MODEL),
        ),
    ]
