# Generated by Django 4.2.7 on 2026-04-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_role_module_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
