# Generated by Django 4.2.7 on 2026-04-29 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0018_alter_rolemodulepermission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='role',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='CustomStaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_staff_roles',
                'ordering': ['name'],
            },
        ),
    ]
