# Generated by Django 4.2.7 on 2026-04-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_custom_staff_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodulepermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
