# Generated by Django 4.2.7 on 2026-04-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0021_staff_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='appointment_letter',
            field=models.FileField(blank=True, null=True, upload_to='staff_docs/appointment/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='id_proof_doc',
            field=models.FileField(blank=True, null=True, upload_to='staff_docs/id_proof/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('voter_id', 'Voter ID'), ('driving', 'Driving Licence'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='qualification_doc',
            field=models.FileField(blank=True, null=True, upload_to='staff_docs/qualification/'),
        ),
    ]
