# Generated by Django 4.2.7 on 2026-05-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_staff_profile_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='aadhar_last4',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='id_proof_doc',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='id_proof_type',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='aadhar_doc',
            field=models.FileField(blank=True, null=True, upload_to='staff_docs/aadhar/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='college_id_doc',
            field=models.FileField(blank=True, null=True, upload_to='staff_docs/college_id/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='college_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
