# Generated by Django 4.2.7 on 2026-05-01 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0023_staff_profile_aadhar_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAmenityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='good', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_amenity_records', to=settings.AUTH_USER_MODEL)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hostel.roomamenity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_records', to='hostel.room')),
            ],
            options={
                'db_table': 'room_amenity_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
