# Generated by Django 4.2.7 on 2026-05-01 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0024_room_amenity_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/attachments/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('students', 'Students Only'), ('staff_all', 'All Staff'), ('warden', 'Wardens'), ('security', 'Security Guards'), ('maintenance', 'Maintenance Staff'), ('mess', 'Mess Staff')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_depts',
            field=models.JSONField(blank=True, default=list, help_text='List of department names'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_gender',
            field=models.CharField(choices=[('all', 'All'), ('boys', 'Boys Hostel'), ('girls', 'Girls Hostel')], default='all', max_length=6),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_years',
            field=models.JSONField(blank=True, default=list, help_text='List of year values e.g. ["1","2"]'),
        ),
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='bi-megaphone', max_length=60)),
                ('color', models.CharField(default='#1565C0', help_text='Hex colour e.g. #1565C0', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ann_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='hostel.announcementcategory'),
        ),
    ]
