# Generated by Django 4.2.7 on 2026-05-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0031_visitor_walkin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='hostel.hostel'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id_proof_type',
            field=models.CharField(default='Aadhar', max_length=50),
        ),
    ]
