# Generated by Django 4.2.7 on 2026-05-02 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0032_visitor_hostel_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='can_edit_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='flag_color',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='flag_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='flag_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='flag_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
