# Generated by Django 4.2.7 on 2026-05-05 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0033_student_flag_editperm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessWastageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Evening Snacks'), ('dinner', 'Dinner')], max_length=15)),
                ('wastage_kg', models.DecimalField(decimal_places=2, help_text='Wastage quantity in kilograms', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_filled', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_records', to='hostel.hostel')),
            ],
            options={
                'db_table': 'mess_wastage_records',
                'ordering': ['-date', 'meal_type'],
                'unique_together': {('hostel', 'date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='MessDailyMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Evening Snacks'), ('dinner', 'Dinner')], max_length=15)),
                ('items', models.TextField()),
                ('original_items', models.TextField(blank=True, help_text='Items as originally uploaded; untouched by edits')),
                ('is_overridden', models.BooleanField(default=False, help_text='True when manually edited after upload')),
                ('upload_month', models.CharField(blank=True, help_text='YYYY-MM of the upload batch this came from', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_menus', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(blank=True, help_text='Null = applies to all hostels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='hostel.hostel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_daily_menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mess_daily_menus',
                'ordering': ['menu_date', 'meal_type'],
                'unique_together': {('hostel', 'menu_date', 'meal_type')},
            },
        ),
    ]
