# Generated by Django 4.2.7 on 2026-05-05 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0034_messwastagerecord_messdailymenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessItemWastage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Evening Snacks'), ('dinner', 'Dinner')], max_length=15)),
                ('item_name', models.CharField(max_length=200)),
                ('prepared_qty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('consumed_qty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('wasted_qty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('litre', 'litre'), ('pcs', 'pcs')], default='kg', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_wastages_filled', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_wastages', to='hostel.hostel')),
            ],
            options={
                'db_table': 'mess_item_wastages',
                'ordering': ['-date', 'meal_type', 'item_name'],
                'unique_together': {('hostel', 'date', 'meal_type', 'item_name')},
            },
        ),
    ]
