# Generated by Django 4.2.7 on 2026-05-05 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0035_messitemwastage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='mess_incharge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mess'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mess_hostels', to=settings.AUTH_USER_MODEL),
        ),
    ]
