# Generated by Django 4.2.7 on 2026-05-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0036_hostel_mess_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messitemwastage',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_wastages', to='hostel.hostel'),
        ),
    ]
