# Generated by Django 4.2.7 on 2026-05-07 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0037_wastage_hostel_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(help_text='Barcode / QR / Tag ID', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_contact', models.CharField(blank=True, max_length=100)),
                ('vendor_invoice', models.CharField(blank=True, max_length=100)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('under_maintenance', 'Under Maintenance'), ('lost', 'Lost'), ('discarded', 'Discarded')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('discarded', 'Discarded'), ('lost', 'Lost')], default='active', max_length=15)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('discard_reason', models.TextField(blank=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['hostel__name', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, default='bi-box-fill', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='is_working_day_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='warden_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='warden_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warden_approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='warden_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10),
        ),
        migrations.CreateModel(
            name='LeaveExtensionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extensions', to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='hostel.leaveapplication')),
            ],
            options={
                'db_table': 'leave_extension_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_days', models.PositiveSmallIntegerField(default=7)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('requires_warden_approval', models.BooleanField(default=True)),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('requires_superadmin_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GatePassCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, help_text='Earliest allowed departure time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Latest expected return time', null=True)),
                ('max_days', models.PositiveSmallIntegerField(default=1, help_text='Maximum allowed duration in days')),
                ('requires_warden_approval', models.BooleanField(default=True)),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('requires_superadmin_approval', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False, help_text='Emergency pass — warden can approve directly')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gate_pass_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('to_floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('transfer_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hostel.asset')),
                ('from_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='hostel.hostel')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='hostel.room')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='hostel.hostel')),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='hostel.room')),
            ],
            options={
                'db_table': 'asset_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('transferred', 'Transferred'), ('condition_changed', 'Condition Changed'), ('discarded', 'Discarded'), ('lost', 'Marked Lost'), ('reassigned', 'Reassigned')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hostel.asset')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hostel.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='discarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discarded_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='asset',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_assets', to='hostel.room'),
        ),
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('event_type', models.CharField(choices=[('working', 'Working Day'), ('sunday', 'Sunday'), ('holiday', 'Public Holiday'), ('emergency_holiday', 'Emergency Holiday'), ('exam', 'Exam Day'), ('festival', 'Festival')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academic_calendar_events',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='gatepass',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='hostel.gatepasscategory'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_applications', to='hostel.leavecategory'),
        ),
    ]
