# Generated by Django 4.2.7 on 2026-05-07 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0039_add_hod_leave_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restriction_type', models.CharField(choices=[('gate_pass', 'Gate Pass'), ('leave', 'Leave'), ('both', 'Gate Pass & Leave')], max_length=10)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('restricted_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_reason', models.TextField(blank=True)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_restrictions', to=settings.AUTH_USER_MODEL)),
                ('restricted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposed_restrictions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='hostel.student')),
            ],
            options={
                'db_table': 'student_restrictions',
                'ordering': ['-restricted_at'],
            },
        ),
    ]
