# Generated by Django 4.2.7 on 2026-05-07 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0040_student_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinerecord',
            name='violation',
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='fine_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='fine_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_fines_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='fine_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='incident_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='notify_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='parent_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='parent_notified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_parent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='room_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='warning_type',
            field=models.CharField(choices=[('none', 'No Warning'), ('verbal', 'Verbal Warning'), ('written', 'Written Warning'), ('final', 'Final Warning')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='disciplinerecord',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='disciplinerecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='DisciplineEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='discipline/evidence/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='document', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='hostel.disciplinerecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discipline_evidence',
            },
        ),
        migrations.CreateModel(
            name='DisciplineCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('default_warning', models.CharField(choices=[('none', 'None'), ('verbal', 'Verbal Warning'), ('written', 'Written Warning'), ('final', 'Final Warning')], default='verbal', max_length=10)),
                ('fine_mandatory', models.BooleanField(default=False)),
                ('notify_parent_auto', models.BooleanField(default=False, help_text='Automatically suggest parent notification for this category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discipline_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Record Created'), ('status_changed', 'Status Changed'), ('warning_issued', 'Warning Issued'), ('fine_added', 'Fine Added'), ('fine_paid', 'Fine Marked Paid'), ('evidence_added', 'Evidence Added'), ('parent_notified', 'Parent Notified'), ('restriction_applied', 'Restriction Applied'), ('note_added', 'Note Added'), ('resolved', 'Record Resolved')], max_length=25)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='hostel.disciplinerecord')),
            ],
            options={
                'db_table': 'discipline_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='hostel.disciplinecategory'),
        ),
    ]
