# Generated by Django 4.2.7 on 2026-06-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0044_student_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='designation',
            field=models.CharField(blank=True, choices=[('incampus', 'InCampus'), ('outcampus', 'OutCampus')], default='', help_text='InCampus or OutCampus — set during bulk upload', max_length=10),
        ),
        migrations.AlterField(
            model_name='gatepasscategory',
            name='max_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Maximum allowed duration in hours'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('plumber', 'Plumber'), ('furniture', 'Furniture'), ('cleaning', 'Cleaning'), ('network', 'Network/Internet'), ('painter', 'Painter'), ('carpentry', 'Carpentry'), ('mason', 'Mason'), ('gardener', 'Gardener'), ('termite', 'Termite Control'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='status',
            field=models.CharField(choices=[('open', 'Open / Unresolved'), ('in_progress', 'Under Process'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='type_of_entry',
            field=models.CharField(blank=True, help_text='Admission category e.g. DRCC, Management, NRI, Sports', max_length=50),
        ),
    ]
