# Generated by Django 4.2.7 on 2026-06-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0045_room_designation_maintenance_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_end_date',
            field=models.DateField(blank=True, help_text='End date for multi-day visits', null=True),
        ),
    ]
