# Generated by Django 4.2.7 on 2026-06-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0046_visitor_state_country_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='gp_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, unique=True),
        ),
    ]
