# Generated by Django 4.2.7 on 2026-06-12 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0047_gatepass_gp_id_length_hostelname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePassSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_prefix', models.CharField(max_length=20, unique=True)),
                ('current_seq', models.PositiveIntegerField(default=1)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gate_pass_sequences',
            },
        ),
    ]
