# Generated by Django 4.2.7 on 2026-06-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0048_gatepasssequence_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepasscategory',
            name='requires_hod_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavecategory',
            name='requires_hod_approval',
            field=models.BooleanField(default=False),
        ),
    ]
