# Generated by Django 4.2.7 on 2026-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0049_hod_approval_gp_leave_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomamenityrecord',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
