# Generated by Django 4.2.7 on 2026-06-12 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0050_roomamenityrecord_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('illness', 'Illness / Fever'), ('injury', 'Injury'), ('hospital', 'Hospital Visit'), ('medicine', 'Medicine Prescribed'), ('ambulance', 'Ambulance Used'), ('other', 'Other')], default='illness', max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('doctor', models.CharField(blank=True, max_length=100)),
                ('medicines', models.TextField(blank=True)),
                ('ambulance_used', models.BooleanField(default=False)),
                ('ambulance_reason', models.TextField(blank=True)),
                ('pickup_location', models.CharField(blank=True, max_length=200)),
                ('drop_location', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hostel.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
