# Generated by Django 4.2.7 on 2026-06-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0051_medicalrecord_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepasssequence',
            name='last_period_key',
            field=models.CharField(blank=True, help_text='Stores week/month/year key to detect period change', max_length=20),
        ),
        migrations.AddField(
            model_name='gatepasssequence',
            name='reset_period',
            field=models.CharField(choices=[('manual', 'Manual Only'), ('weekly', 'Weekly (every Monday)'), ('monthly', 'Monthly (1st of each month)'), ('yearly', 'Yearly (1st Jan each year)')], default='manual', max_length=10),
        ),
    ]
