# Generated by Django 4.2.7 on 2026-03-31 07:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=10)),
                ('semester', models.PositiveSmallIntegerField()),
                ('room_type', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=10)),
                ('hostel_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mess_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_fee_label', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fee_structures',
            },
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('waived', 'Waived')], default='pending', max_length=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='hostel.student')),
            ],
            options={
                'db_table': 'fee_records',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'fee_structure')},
            },
        ),
    ]
