# Generated by Django 4.2.7 on 2026-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin 2'), ('warden', 'Warden'), ('student', 'Student'), ('security', 'Security Guard')], default='student', max_length=10),
        ),
    ]
