# Generated by Django 4.2.7 on 2026-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_superadmin_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Admin 1'), ('admin', 'Admin 2'), ('warden', 'Warden'), ('student', 'Student'), ('security', 'Security Guard'), ('maintenance', 'Maintenance Incharge'), ('mess', 'Mess Management')], default='student', max_length=40),
        ),
    ]
