# Generated by Django 4.2.7 on 2026-05-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_custom_role_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department name — required for HOD role', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Admin 1'), ('admin', 'Admin 2'), ('warden', 'Warden'), ('hod', 'HOD'), ('student', 'Student'), ('security', 'Security Guard'), ('maintenance', 'Maintenance Incharge'), ('mess', 'Mess Management')], default='student', max_length=40),
        ),
    ]
